### ISSUE TITLE
[BUG] Data in the Score tab not updated properly

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#72] opened 2017-03-25 19:12 UTC
1. Round (only me and expl. are playing):
![speed 2017-03-25 19-57-04-383](https://cloud.githubusercontent.com/assets/803239/24325315/2a3c4710-118e-11e7-80e9-04d39590456a.jpg)
   1. Problem: no data in cmb, spm, sent, blocked on Expl.'s part.
   2. Problem: Def is afk the whole time
then I went afk.

2. Round:
![speed 2017-03-25 20-01-20-004](https://cloud.githubusercontent.com/assets/803239/24325316/2f72d870-118e-11e7-9adb-f88a0a7a81cc.jpg)
Notice that my data from the first round is still presented and also the data from Def who is still afk.

**Comment by zDEFz** [comment] 2017-03-25 19:27
**This is me after AFK and a Disconnect caused by ISP**

![image](https://cloud.githubusercontent.com/assets/24463722/24325442/69add52a-1199-11e7-99c3-d15639ac16bf.png)

**Comment by Noir-** [comment] 2017-04-04 23:29
Can someone confirm that this is fixed now?

**Closed as completed** 2017-05-12 11:15 UTC
Labels: bug
